pipeline{
    agent any
   tools{
    maven 'M2_HOME'
   }

    stages{
        stage('sonacloud analysis'){
                steps{
                     withSonarQubeEnv('sonarcloud'){
                        sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Eng-Mike_devops-testddt'

                     }
                
            }
            }
            
        }
    }
